language: rust

# Cache cargo artifact to speed up the build
# https://docs.travis-ci.com/user/languages/rust#dependency-management
cache: cargo

env:
  # Forbid linting warnings
  # https://doc.rust-lang.org/rustc/command-line-arguments.html#a-d-set-lint-denied
  - RUSTFLAGS="-D warnings"

# Install rust utilities
before_script:
- rustup component add rustfmt clippy

script:
  - cargo build --verbose --all
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test --verbose --all
  - cargo run --bin test-runner ./tests/fixtures