[package]
name = "weaselm"
version = "0.1.0"
authors = ["Pierre-Marie Dartus <p.dartus@salesforce.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"