version: 2
jobs:
  build:
    docker:
      - image:  circleci/rust:1
    steps:
      - checkout
      - run: 
          name: Build all
          command: cargo build --verbose --all
      - run: 
          name: Test all
          command: cargo test --verbose --all
